import assert from "node:assert/strict";
import { after, test } from "node:test";
import { readFileSync } from "node:fs";
import { validateCurriculumCatalog } from "./curriculum.mjs";
import { GATE4C_CURRICULUM_CATALOG_VERSION, GATE4C_MAX_LESSONS, GATE4C_TOKEN_BUDGET } from "./formats.mjs";
import { acceptedFixture, approval, approvedEvent, learningEvent, lifecycle, NOW, PROJECTION_PRIVATE_CANARY } from "./fixtures.mjs";
import { buildApprovedKnowledgeProjection, projectionStatus, retrieveApprovedKnowledge, safeRetrieveApprovedKnowledge } from "./projection.mjs";

const covered = new Set();
const caseTest = (id, name, fn) => test(`[${id}] ${name}`, async () => { covered.add(id); await fn(); });
const expectCode = (fn, code) => assert.throws(fn, error => error.code === code);
const scope = (participantId = null, projectId = null, capabilities = []) => ({ participantId, projectId, capabilities });
function build(payloads) { const fixture = acceptedFixture(payloads); return { ...fixture, projection: buildApprovedKnowledgeProjection({ source: fixture.source, cipher: fixture.cipher, now: NOW }) }; }
function query(value, task, requestScope = scope(), options = {}) { return retrieveApprovedKnowledge({ projection: value.projection, currentManifestHmac: value.projection.sourceManifestHmac, requestScope, task, cipher: value.cipher, now: NOW, ...options }); }

caseTest("G4C-01", "accepted Gate 4B chain is authenticated and revalidated", () => { const value = build(approvedEvent("global-one", { lesson: "verify bounded evidence", scope: "global" })); assert.equal(value.projection.activeLessonCount, 1); assert.equal(value.projection.sourceAuthority, "accepted-gate4b-journal"); });
caseTest("G4C-02", "tampered authenticated source record is denied", () => { const value = acceptedFixture(approvedEvent("global-two")); const records = value.source.records.map(item => structuredClone(item)); records[0].privateEnvelope.tag = Buffer.alloc(16).toString("base64"); expectCode(() => buildApprovedKnowledgeProjection({ source: { ...value.source, records }, cipher: value.cipher, now: NOW }), "private-envelope-invalid"); });
caseTest("G4C-03", "changed accepted manifest is denied", () => { const value = acceptedFixture(approvedEvent("global-three")); expectCode(() => buildApprovedKnowledgeProjection({ source: { ...value.source, manifestHmac: "0".repeat(64) }, cipher: value.cipher, now: NOW }), "projection-source-manifest-mismatch"); });
caseTest("G4C-04", "unapproved and inactive lessons do not project", () => { const payloads = [["learning-event", learningEvent("unapproved")], ...approvedEvent("active", { lesson: "active bounded guidance" })]; const value = build(payloads); assert.equal(value.projection.activeLessonCount, 1); assert.equal(value.projection.lessons[0].lesson, "active bounded guidance"); });
caseTest("G4C-05", "an approved correction supersedes its approved predecessor", () => { const payloads = [...approvedEvent("old", { lesson: "old repository guidance" }), ["learning-event", learningEvent("new", { lesson: "new repository guidance", corrects: ["old"] })], ["approval", approval("approval-new", "new")], ["lifecycle", lifecycle("correct", "old", { replacementEventId: "new" })]]; const value = build(payloads); assert.deepEqual(value.projection.lessons.map(item => item.lesson), ["new repository guidance"]); });
caseTest("G4C-06", "revoked and approval-expired lessons are excluded", () => { const payloads = [...approvedEvent("revoked"), ["approval", approval("revoke-revoked", "revoked", "revoke", "approval-revoked")], ...approvedEvent("expired-approval"), ["approval", approval("expire-expired", "expired-approval", "expire", "approval-expired-approval")]]; assert.equal(build(payloads).projection.activeLessonCount, 0); });
caseTest("G4C-07", "event expiry deletion-due and deletion are excluded", () => { const payloads = [...approvedEvent("event-expired", { expiresAt: "2026-08-21T14:00:00.000Z" }), ...approvedEvent("deletion-due", { deletionRequiredBy: "2026-08-21T14:00:00.000Z" }), ...approvedEvent("deleted"), ["lifecycle", lifecycle("delete", "deleted")]]; assert.equal(build(payloads).projection.activeLessonCount, 0); });
caseTest("G4C-08", "safe hold excludes and reviewed release restores", () => { const held = build([...approvedEvent("held"), ["lifecycle", lifecycle("safe-hold-proposed", "held")]]); assert.equal(held.projection.activeLessonCount, 0); const released = build([...approvedEvent("released"), ["lifecycle", lifecycle("safe-hold-proposed", "released", { effectiveAt: "2026-08-21T13:00:00.000Z" })], ["lifecycle", lifecycle("release-safe-hold", "released")]]); assert.equal(released.projection.activeLessonCount, 1); });
caseTest("G4C-09", "participant project and capabilities must all be declared", () => { const value = build(approvedEvent("scope-required")); expectCode(() => query(value, "scope guidance", { participantId: null, projectId: null }), "projection-request-scope-required"); });
caseTest("G4C-10", "personal knowledge requires the exact verified participant", () => { const value = build(approvedEvent("personal-one", { lesson: "private preference guidance", scope: "personal", scopeId: "matthew-owner" })); assert.equal(query(value, "private preference", scope(null)).selected, false); assert.equal(query(value, "private preference", scope("someone-else")).selected, false); assert.equal(query(value, "private preference", scope("matthew-owner")).selected, true); });
caseTest("G4C-11", "project knowledge fails closed when undeclared or mismatched", () => { const value = build(approvedEvent("project-one", { lesson: "project deployment guidance", scope: "project", scopeId: "runaai-next" })); assert.equal(query(value, "project deployment", scope(null, null)).selected, false); assert.equal(query(value, "project deployment", scope(null, "other")).selected, false); assert.equal(query(value, "project deployment", scope(null, "runaai-next")).selected, true); });
caseTest("G4C-12", "capability knowledge requires an explicitly declared capability", () => { const value = build(approvedEvent("cap-one", { lesson: "external research boundary", scope: "capability", scopeId: "external-research" })); assert.equal(query(value, "external research", scope()).selected, false); assert.equal(query(value, "external research", scope(null, null, ["workspace-read"])).selected, false); assert.equal(query(value, "external research", scope(null, null, ["external-research"])).selected, true); });
caseTest("G4C-13", "session evaluation and training candidates never advise", () => { const payloads = [...approvedEvent("session-one", { scope: "session", scopeId: "session-1" }), ...approvedEvent("eval-one", { scope: "evaluation", scopeId: "eval-1" }), ...approvedEvent("training-one", { scope: "training-candidate", scopeId: "train-1" })]; const value = build(payloads); const result = query(value, PROJECTION_PRIVATE_CANARY, scope("matthew-owner", "runaai-next", ["external-research"])); assert.equal(result.selected, false); assert.equal(result.scopeFiltering.excludedCount, 3); });
caseTest("G4C-14", "scope filters before an out-of-scope high relevance lesson can rank", () => { const payloads = [...approvedEvent("wrong-project", { lesson: "deployment deployment deployment exact answer", scope: "project", scopeId: "other" }), ...approvedEvent("right-project", { lesson: "deployment answer", scope: "project", scopeId: "runaai-next" })]; const value = build(payloads); const result = query(value, "deployment exact answer", scope(null, "runaai-next")); assert.equal(result.selected, true); assert.equal(result.context.lessons[0].lesson, "deployment answer"); assert.equal(result.scopeFiltering.excludedCount, 1); });
caseTest("G4C-15", "identical projection queries are deterministic", () => { const value = build([...approvedEvent("det-a", { lesson: "bounded evidence alpha" }), ...approvedEvent("det-b", { lesson: "bounded evidence beta" })]); assert.deepEqual(query(value, "bounded evidence"), query(value, "bounded evidence")); });
caseTest("G4C-16", "one weak shared term returns one lesson", () => { const payloads = Array.from({ length: 8 }, (_, index) => approvedEvent(`weak-${index}`, { lesson: `shared lesson ${index}` })).flat(); const result = query(build(payloads), "shared"); assert.equal(result.selectedCount, 1); });
caseTest("G4C-17", "selection observes both lesson and token bounds", () => { const countPayloads = Array.from({ length: 10 }, (_, index) => approvedEvent(`count-${index}`, { lesson: `bounded evidence topic ${index}` })).flat(); const count = query(build(countPayloads), "bounded evidence topic"); assert.ok(count.selectedCount <= GATE4C_MAX_LESSONS); const large = query(build([...approvedEvent("large-a", { lesson: `budget topic ${"x".repeat(3900)}` }), ...approvedEvent("large-b", { lesson: `budget topic ${"y".repeat(3900)}` })]), "budget topic"); assert.ok(large.context.estimatedTokens <= GATE4C_TOKEN_BUDGET); });
caseTest("G4C-18", "must-not-apply text prevents advisory selection", () => { const value = build(approvedEvent("forbidden", { lesson: "production deployment guidance", mustNotApply: ["when production is active"] })); assert.equal(query(value, "production deployment when production is active").selected, false); });
caseTest("G4C-19", "selected provenance is keyed and omits legacy ids", () => { const value = build(approvedEvent("provenance-event", { lesson: "provenance evidence guidance" }, "provenance-approval")); const result = query(value, "provenance evidence"); assert.equal(result.references.length, 1); assert.doesNotMatch(JSON.stringify(result.references), /provenance-event|provenance-approval|sha256:/); assert.match(result.references[0].eventRefHmac, /^[a-f0-9]{64}$/); });
caseTest("G4C-20", "a changed accepted journal head makes the projection stale", () => { const value = build(approvedEvent("stale")); expectCode(() => retrieveApprovedKnowledge({ projection: value.projection, currentManifestHmac: "f".repeat(64), requestScope: scope(), task: "stale guidance", cipher: value.cipher, now: NOW }), "projection-stale"); });
caseTest("G4C-21", "a reached lifecycle boundary requires projection rebuild", () => { const fixture = acceptedFixture(approvedEvent("future-expiry", { lesson: "future expiry guidance", expiresAt: "2026-08-21T16:00:00.000Z" })); const projection = buildApprovedKnowledgeProjection({ source: fixture.source, cipher: fixture.cipher, now: NOW }); expectCode(() => retrieveApprovedKnowledge({ projection, currentManifestHmac: projection.sourceManifestHmac, requestScope: scope(), task: "future expiry", cipher: fixture.cipher, now: "2026-08-21T16:00:00.000Z" }), "projection-lifecycle-reevaluation-required"); });
caseTest("G4C-22", "a structurally plausible fabricated projection is rejected", () => { const fixture = acceptedFixture(approvedEvent("fake")); expectCode(() => retrieveApprovedKnowledge({ projection: { schemaVersion: "runa2-approved-knowledge-projection/v1", lessons: [] }, currentManifestHmac: "0".repeat(64), requestScope: scope(), task: "fake", cipher: fixture.cipher, now: NOW }), "projection-instance-invalid"); });
caseTest("G4C-23", "safe failure returns no advisory context", () => { const result = safeRetrieveApprovedKnowledge({ projection: {}, requestScope: scope(), task: "anything" }); assert.equal(result.selected, false); assert.equal(result.context, null); assert.equal(result.modelContextAuthorized, false); });
caseTest("G4C-24", "curricula validate only as inactive candidate templates", () => { const catalog = validateCurriculumCatalog({ schemaVersion: GATE4C_CURRICULUM_CATALOG_VERSION, catalogId: "foundation-v1", lessons: [{ id: "identity", text: "Runa identity guidance", scope: "global", scopeId: null, sources: ["system-profile"] }] }); assert.equal(catalog.candidateTemplatesOnly, true); assert.equal(catalog.approved, false); assert.equal(catalog.activated, false); assert.equal(catalog.mutationInterfaceAvailable, false); });
caseTest("G4C-25", "selected advisory data cannot grant any action authority", () => { const result = query(build(approvedEvent("authority", { lesson: "authority boundary guidance" })), "authority boundary"); for (const field of ["mayAuthorizeAction", "toolPermissionAllowed", "filePermissionAllowed", "networkPermissionAllowed", "spendingPermissionAllowed", "workerPermissionAllowed", "trainingAllowed", "policyChangeAllowed", "identityChangeAllowed"]) { assert.equal(result[field], false); assert.equal(result.context[field], false); } assert.equal(result.modelContextAuthorized, false); });
caseTest("G4C-26", "projection status is aggregate-only and inactive", () => { const value = build(approvedEvent("status-private")); const status = projectionStatus(value.projection); assert.equal(status.privateValuesEmitted, false); assert.equal(status.modelContextActivated, false); assert.equal(status.qdrantActivated, false); assert.equal(JSON.stringify(status).includes(PROJECTION_PRIVATE_CANARY), false); });
caseTest("G4C-27", "a correction lifecycle that contradicts the event relationship fails closed", () => { const payloads = [...approvedEvent("lineage-old"), ["learning-event", learningEvent("lineage-new")], ["lifecycle", lifecycle("correct", "lineage-old", { replacementEventId: "lineage-new" })]]; const fixture = acceptedFixture(payloads); expectCode(() => buildApprovedKnowledgeProjection({ source: fixture.source, cipher: fixture.cipher, now: NOW }), "projection-correction-lineage-invalid"); });
caseTest("G4C-28", "two active approvals for one event fail closed", () => { const payloads = [["learning-event", learningEvent("double-approved")], ["approval", approval("approval-double-one", "double-approved")], ["approval", approval("approval-double-two", "double-approved")]]; const fixture = acceptedFixture(payloads); expectCode(() => buildApprovedKnowledgeProjection({ source: fixture.source, cipher: fixture.cipher, now: NOW }), "projection-approval-lineage-invalid"); });

after(() => { const corpus = JSON.parse(readFileSync(new URL("./PARITY-CORPUS.json", import.meta.url), "utf8")); assert.deepEqual([...covered].sort(), corpus.cases.map(item => item.id).sort()); });
