import assert from "node:assert/strict";
import { after, test } from "node:test";
import { readFileSync } from "node:fs";
import { MemoryGate4bStore } from "./adapters/memory.mjs";
import { parseGate4bSnapshot } from "./contracts.mjs";
import { PRIVATE_CANARY, PARTICIPANT, makeSnapshot, testCipher } from "./fixtures.mjs";
import { inventoryFromSnapshot, safeInventoryOutput } from "./inventory.mjs";
import { buildGate4bPlan, Gate4bMigrationService } from "./migration.mjs";

const covered = new Set();
const caseTest = (id, name, fn) => test(`[${id}] ${name}`, async () => { covered.add(id); await fn(); });
const expectCode = async (operation, code) => { try { await operation(); assert.fail(`expected ${code}`); } catch (error) { assert.equal(error.code, code); } };
const setup = async () => { const store = new MemoryGate4bStore(); const cipher = testCipher(); const service = new Gate4bMigrationService({ store, cipher }); const snapshot = makeSnapshot(); const result = await service.migrate(snapshot, { runId: "run-1" }); return { store, cipher, service, snapshot, result }; };

caseTest("G4B-01", "exact ordered journal history survives an encrypted round trip", async () => {
  const { store, cipher } = await setup(); assert.equal(store.state.records.length, 6);
  for (const row of store.state.records) { const context = { recordType: "learning-journal-entry", participantId: PARTICIPANT, recordId: row.targetId, field: "legacy-entry" }; const entry = cipher.decrypt(context, row.privateEnvelope); assert.equal(entry.sequence, row.sequence); assert.equal(entry.entryDigest, row.sourceEntryDigest); }
});
caseTest("G4B-02", "all five entry kinds and approval batch history are retained", async () => { const { store } = await setup(); assert.deepEqual(store.state.indexes.map(row => row.entryKind), ["learning-event", "outcome-feedback", "approval-batch", "learning-event", "lifecycle", "approval"]); assert.equal(store.state.indexes[2].approvalCount, 1); });
caseTest("G4B-03", "same run replay is idempotent", async () => { const { store, service, snapshot } = await setup(); assert.equal((await service.migrate(snapshot, { runId: "run-1" })).replayed, true); assert.equal((await store.auditState()).runs, 1); });
caseTest("G4B-04", "same run id with changed source conflicts", async () => { const { service } = await setup(); const changed = makeSnapshot({ mutatePayloads: values => { values[0][1].eventType = "direct-teaching"; } }); await expectCode(() => service.migrate(changed, { runId: "run-1" }), "migration-run-conflict"); });
caseTest("G4B-05", "an approved successor may append but never rewrite history", async () => { const { store, service, result } = await setup(); const next = makeSnapshot({ sourceSnapshotId: "synthetic-learning-2", predecessorManifestHmac: result.manifestHmac, extraEntry: true }); const committed = await service.migrate(next, { runId: "run-2" }); assert.equal(committed.appendedEntries, 1); assert.equal((await store.auditState()).records, 7); });
caseTest("G4B-06", "a successor cannot shrink accepted history", async () => { const { service, result } = await setup(); const short = makeSnapshot({ sourceSnapshotId: "short", predecessorManifestHmac: result.manifestHmac, mutate: value => { value.entries.pop(); return value; } }); short.entries.at(-1).entryDigest = short.entries.at(-1).entryDigest; await expectCode(() => service.migrate(short, { runId: "short" }), "migration-append-only-violation"); });
caseTest("G4B-07", "a valid alternate chain cannot rewrite the accepted prefix", async () => { const { service, result } = await setup(); const rewrite = makeSnapshot({ sourceSnapshotId: "rewrite", predecessorManifestHmac: result.manifestHmac, mutatePayloads: values => { values[0][1].eventType = "direct-teaching"; } }); await expectCode(() => service.migrate(rewrite, { runId: "rewrite" }), "migration-append-only-violation"); });
caseTest("G4B-08", "failure before commit is atomic and retry completes once", async () => { const store = new MemoryGate4bStore(); const service = new Gate4bMigrationService({ store, cipher: testCipher() }); await expectCode(() => service.migrate(makeSnapshot(), { runId: "before", failBeforeCommit: true }), "migration-simulated-before-commit"); assert.equal((await store.auditState()).records, 0); assert.equal((await service.migrate(makeSnapshot(), { runId: "before" })).committed, true); });
caseTest("G4B-09", "response loss after commit replays one result", async () => { const store = new MemoryGate4bStore(); const service = new Gate4bMigrationService({ store, cipher: testCipher() }); await expectCode(() => service.migrate(makeSnapshot(), { runId: "lost", failAfterCommit: true }), "migration-response-lost"); assert.equal((await service.migrate(makeSnapshot(), { runId: "lost" })).replayed, true); assert.equal((await store.auditState()).runs, 1); });
caseTest("G4B-10", "unknown schema and broken digest fail closed", async () => { await expectCode(() => Promise.resolve(parseGate4bSnapshot(makeSnapshot({ mutate: value => { value.schemaVersion = "unknown"; return value; } }))), "migration-source-invalid"); await expectCode(() => Promise.resolve(parseGate4bSnapshot(makeSnapshot({ mutate: value => { value.entries[0].payloadDigest = `sha256:${"0".repeat(64)}`; return value; } }))), "migration-source-digest-invalid"); });
caseTest("G4B-11", "sequence gaps and prior-link breaks fail closed", async () => { await expectCode(() => Promise.resolve(parseGate4bSnapshot(makeSnapshot({ mutate: value => { value.entries[2].sequence = 9; return value; } }))), "migration-source-chain-invalid"); await expectCode(() => Promise.resolve(parseGate4bSnapshot(makeSnapshot({ mutate: value => { value.entries[1].previousEntryDigest = null; return value; } }))), "migration-source-chain-invalid"); });
caseTest("G4B-12", "outcome, lifecycle, and approval lineage must point backward", async () => { const invalid = makeSnapshot({ mutatePayloads: values => { values[1][1].outcomeEventRef.eventId = "event-missing"; } }); await expectCode(() => Promise.resolve(parseGate4bSnapshot(invalid)), "migration-source-lineage-invalid"); });
caseTest("G4B-13", "private lessons appear only inside authenticated envelopes", async () => { const plan = buildGate4bPlan(makeSnapshot(), testCipher()); assert.equal(JSON.stringify(plan.indexes).includes(PRIVATE_CANARY), false); assert.equal(JSON.stringify(plan.records).includes(PRIVATE_CANARY), false); assert.equal(JSON.stringify(plan).includes(PRIVATE_CANARY), false); });
caseTest("G4B-14", "swapped or tampered envelopes fail their record binding", async () => { const { store, cipher } = await setup(); const first = store.state.records[0]; const second = store.state.records[1]; const context = { recordType: "learning-journal-entry", participantId: PARTICIPANT, recordId: first.targetId, field: "legacy-entry" }; assert.throws(() => cipher.decrypt(context, second.privateEnvelope), error => error.code === "private-envelope-invalid"); assert.throws(() => cipher.decrypt(context, { ...first.privateEnvelope, tag: Buffer.alloc(16).toString("base64") }), error => error.code === "private-envelope-invalid"); });
caseTest("G4B-15", "migration preserves approvals but activates no projection", async () => { const { result, store } = await setup(); assert.equal(result.projectionActivated, false); assert.equal((await store.auditState()).projectionActivated, false); assert.equal(typeof store.readApprovedKnowledge, "undefined"); });
caseTest("G4B-16", "aggregate inventory is deterministic and content free", async () => { const first = inventoryFromSnapshot(makeSnapshot()); const second = inventoryFromSnapshot(makeSnapshot()); const output = safeInventoryOutput({ authority: { commit: "1".repeat(40), clean: true, ownerIdentity: "Matthew" }, first, second, sourcePinsVerified: true }); assert.equal(output.passed, true); assert.equal(output.disallowedFieldsEmitted, false); assert.equal(JSON.stringify(output).includes(PRIVATE_CANARY), false); assert.equal(output.aggregate.stores.eventJournal.entries, 6); });
caseTest("G4B-17", "inventory distinguishes empty, unreadable, and integrity failure", async () => { const empty = inventoryFromSnapshot(makeSnapshot({ mutate: value => { value.entries = []; return value; } })); assert.equal(empty.passed, true); assert.equal(empty.stores.eventJournal.entries, 0); assert.equal(inventoryFromSnapshot(makeSnapshot(), { unreadableEntries: 1 }).passed, false); assert.equal(inventoryFromSnapshot(makeSnapshot(), { integrityFindings: 1 }).passed, false); });
caseTest("G4B-18", "protected inventory output fails closed on authority or pin mismatch", async () => { const first = inventoryFromSnapshot(makeSnapshot()); assert.throws(() => safeInventoryOutput({ authority: { commit: "1".repeat(40), clean: false, ownerIdentity: "Matthew" }, first, second: first, sourcePinsVerified: true }), error => error.code === "inventory-authority-mismatch"); assert.throws(() => safeInventoryOutput({ authority: { commit: "1".repeat(40), clean: true, ownerIdentity: "Matthew" }, first, second: first, sourcePinsVerified: false }), error => error.code === "inventory-authority-mismatch"); });
caseTest("G4B-19", "legacy E3 E4 E5 and vault disposition stays explicitly unresolved", async () => { const inventory = inventoryFromSnapshot(makeSnapshot()); for (const key of ["legacyInboxE3", "legacyReviewE4", "legacyGrantE5", "deviceVault"]) assert.deepEqual(inventory.stores[key], { present: null, records: null, unreadable: null }); });
caseTest("G4B-20", "dependency failure leaves the source snapshot available", async () => { const source = makeSnapshot(); const service = new Gate4bMigrationService({ cipher: testCipher(), store: { async commitSnapshot() { throw Object.assign(new Error("offline"), { code: "dependency-unavailable" }); } } }); await expectCode(() => service.migrate(source, { runId: "offline" }), "dependency-unavailable"); assert.equal(source.entries.length, 6); });

after(() => { const corpus = JSON.parse(readFileSync(new URL("./PARITY-CORPUS.json", import.meta.url), "utf8")); assert.deepEqual([...covered].sort(), corpus.cases.map(item => item.id).sort()); });
