import { parseGate4bSnapshot } from "./contracts.mjs";
const coded = (code, message) => Object.assign(new Error(message), { code });
const KINDS = ["learning-event", "outcome-feedback", "lifecycle", "approval", "approval-batch"];
function tally(values) { const result = {}; for (const value of values) if (typeof value === "string" && value) result[value] = (result[value] ?? 0) + 1; return Object.fromEntries(Object.entries(result).sort(([a], [b]) => a.localeCompare(b))); }
export function inventoryFromSnapshot(raw, diagnostics = {}) {
  const snapshot = parseGate4bSnapshot(raw); const byKind = Object.fromEntries(KINDS.map(kind => [kind, snapshot.entries.filter(entry => entry.kind === kind).length])); const learningEvents = snapshot.entries.filter(entry => entry.kind === "learning-event"); const lifecycle = snapshot.entries.filter(entry => entry.kind === "lifecycle"); const approvals = snapshot.entries.flatMap(entry => entry.kind === "approval" ? [entry.payload] : entry.kind === "approval-batch" ? entry.payload.approvals : []); const unreadableEntries = Number(diagnostics.unreadableEntries ?? 0); const integrityFindings = Number(diagnostics.integrityFindings ?? 0); const unresolvedLineage = Number(diagnostics.unresolvedLineage ?? 0);
  return { schemaVersion: "runa2-gate4b-owner-inventory-aggregate/v1", stores: { eventJournal: { present: true, entries: snapshot.entries.length, byKind, earliestRecordedAt: snapshot.entries[0]?.recordedAt ?? null, latestRecordedAt: snapshot.entries.at(-1)?.recordedAt ?? null, unreadableEntries, integrityFindings, unresolvedLineage }, legacyInboxE3: diagnostics.legacyInboxE3 ?? { present: null, records: null, unreadable: null }, legacyReviewE4: diagnostics.legacyReviewE4 ?? { present: null, records: null, unreadable: null }, legacyGrantE5: diagnostics.legacyGrantE5 ?? { present: null, records: null, unreadable: null }, deviceVault: diagnostics.deviceVault ?? { present: null, records: null, unreadable: null } }, learningEvents: { byEventType: tally(learningEvents.map(entry => entry.payload.eventType)), byDestination: tally(learningEvents.map(entry => entry.payload.destination?.tier)), byScope: tally(learningEvents.map(entry => entry.payload.scope?.proposedReuse)) }, lifecycle: { byAction: tally(lifecycle.map(entry => entry.payload.action)) }, approvals: { byAction: tally(approvals.map(item => item.action)) }, passed: unreadableEntries === 0 && integrityFindings === 0 && unresolvedLineage === 0 };
}
export function safeInventoryOutput({ authority, first, second, sourcePinsVerified }) {
  if (!authority || !/^[a-f0-9]{40}$/.test(authority.commit ?? "") || authority.clean !== true || authority.ownerIdentity !== "Matthew" || sourcePinsVerified !== true) throw coded("inventory-authority-mismatch", "Protected inventory authority or source pins did not match.");
  const deterministicSecondPass = JSON.stringify(first) === JSON.stringify(second);
  return { schemaVersion: "runa2-gate4b-owner-inventory-result/v1", authority: { commit: authority.commit, clean: true, ownerIdentityVerified: true, sourcePinsVerified: true }, aggregate: structuredClone(first), deterministicSecondPass, disallowedFieldsEmitted: false, passed: deterministicSecondPass && first.passed === true };
}
