import assert from "node:assert/strict";
import { test } from "node:test";
import { assertOwnerInventoryAuthority, runOwnerInventory } from "./owner-inspection.mjs";

const commitA = "a".repeat(40); const commitB = "b".repeat(40);
function aggregate(extra = {}) { return { schemaVersion: "runa2-gate4b-owner-inventory-aggregate/v1", stores: { eventJournal: { present: true, entries: 6, byKind: { "learning-event": 2, "outcome-feedback": 1, lifecycle: 1, approval: 1, "approval-batch": 1 }, encryptedBytes: 600, maximumEncryptedEntryBytes: 100, unreadableEntries: 0, integrityFindings: 0, unresolvedLineage: 0 }, legacyInboxE3: { present: true, records: 2, tombstones: 1, unreadable: 0 }, legacyReviewE4: { present: true, records: 2, authorityRecords: 1, retrievalCapsules: 1, evaluationCapsules: 0, unreadable: 0 }, legacyGrantE5: { present: true, records: 1, events: 0, unreadable: 0 }, deviceVault: { present: true, records: 1, unreadable: 0 } }, learningEvents: { byEventType: { "user-correction": 2 }, byDestination: { personal: 2 }, byScope: { personal: 2 } }, lifecycle: { byState: { "candidate-recorded": 2 }, held: 0 }, approvals: { totalEvents: 2, active: 1, byState: { "active-until-revoked": 1, "revoked-or-expired": 1 }, actionCountsAvailable: false }, passed: true, ...extra }; }
const authority = { legacyCommit: commitA, nextCommit: commitB, clean: true, ownerIdentityVerified: true, sourcePinsVerified: true };

test("owner inventory runs two passes and emits only aggregate allowlisted fields", async () => { let calls = 0; const output = await runOwnerInventory({ authority, inspect: async () => { calls += 1; return aggregate({ privateLesson: "PRIVATE_OWNER_CANARY" }); } }); assert.equal(calls, 2); assert.equal(output.passed, true); assert.equal(output.disallowedFieldsEmitted, false); assert.equal(JSON.stringify(output).includes("PRIVATE_OWNER_CANARY"), false); });
test("owner inventory fails when the second aggregate differs", async () => { let calls = 0; const output = await runOwnerInventory({ authority, inspect: async () => aggregate(calls++ ? { stores: { ...aggregate().stores, deviceVault: { present: true, records: 1, unreadable: 1 } } } : {}) }); assert.equal(output.deterministicSecondPass, false); assert.equal(output.passed, false); });
test("unknown aggregate categories fail before output", async () => { await assert.rejects(() => runOwnerInventory({ authority, inspect: async () => aggregate({ learningEvents: { ...aggregate().learningEvents, byEventType: { "private-lesson-value": 1 } } }) }), error => error.code === "inventory-aggregate-invalid"); });
test("authority checks identity, both clean commits, branch, and every source pin before inspection", () => { const calls = []; const exec = (file, args) => { calls.push([file, args]); if (file === "hostname") return "RUNA-CONTROL\n"; if (file === "whoami") return "RUNA-CONTROL\\Matthew\n"; const tail = args.slice(4); if (tail[0] === "rev-parse" && tail[1] === "HEAD") return `${args[3].includes("legacy") ? commitA : commitB}\n`; if (tail[0] === "branch") return `${args[3].includes("legacy") ? "main" : "runa2/gate-4b-learning-events-plan"}\n`; if (tail[0] === "status") return ""; if (tail[0] === "rev-parse" && tail[1].startsWith("HEAD:")) return "c".repeat(40); throw new Error(JSON.stringify(args)); }; const checked = assertOwnerInventoryAuthority({ legacyRepo: "C:\\legacy", nextRepo: "C:\\next", expectedLegacyCommit: commitA, expectedNextCommit: commitB, sourcePins: { sources: [{ path: "one.mjs", gitBlobSha1: "c".repeat(40) }] }, exec }); assert.equal(checked.ownerIdentityVerified, true); assert.equal(calls.at(-1)[1].at(-1), "HEAD:one.mjs"); });
test("authority mismatch stops before source pin inspection", () => { let calls = 0; const exec = file => { calls += 1; return file === "hostname" ? "OTHER\n" : "user\n"; }; assert.throws(() => assertOwnerInventoryAuthority({ legacyRepo: "C:\\legacy", nextRepo: "C:\\next", expectedLegacyCommit: commitA, expectedNextCommit: commitB, sourcePins: { sources: [] }, exec }), error => error.code === "inventory-owner-authority-mismatch"); assert.equal(calls, 2); });
