param([ValidateSet('Upload','Dispatch','Status','Export','Cleanup','Final')][string]$Mode,[string]$LeaseId,[string]$ExpectedSeal,[string]$LocalFile)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
if($LeaseId-notmatch'^20260829-campaign-(gemma|coder|qwen36)-r[1-9][0-9]*$'){throw 'lease-v2-id'}
if($ExpectedSeal-notmatch'^[a-f0-9]{64}$'){throw 'lease-v2-seal'}
$root='C:\Users\codex-audit\AppData\Local\RunaM1Readiness\'+$LeaseId
$remote='$ErrorActionPreference=''Stop'';$ProgressPreference=''SilentlyContinue'';'
if($Mode-eq'Upload'){
 $remote+='if(Test-Path -LiteralPath '''+$root+'''){throw ''lease-v2-root-exists''};[IO.Directory]::CreateDirectory('''+$root+''')|Out-Null;$s=[IO.File]::Open('''+$root+'\transfer.json'',[IO.FileMode]::CreateNew,[IO.FileAccess]::Write);try{[Console]::OpenStandardInput().CopyTo($s)}finally{$s.Dispose()};$packet=Get-Content -LiteralPath '''+$root+'\transfer.json'' -Raw|ConvertFrom-Json;$allowed=@(''home-campaign-lease-v2.mjs'',''lease-v2-contract.mjs'',''lease-contract.mjs'',''Run-HomeCampaignLeaseV2.ps1'',''gguf-metadata.mjs'',''runtime.json'',''lease-config.json'',''seal.json'',''campaign-hardware-plan.json'');if((($packet.PSObject.Properties.Name|Sort-Object)-join'','')-ne(($allowed|Sort-Object)-join'','')){throw ''lease-v2-package-files''};foreach($f in $packet.PSObject.Properties){$s=[IO.File]::Open((Join-Path '''+$root+''' $f.Name),[IO.FileMode]::CreateNew,[IO.FileAccess]::Write);try{$b=[Convert]::FromBase64String($f.Value);$s.Write($b,0,$b.Length)}finally{$s.Dispose()}};'
}
$remote+='if((Get-FileHash -LiteralPath '''+$root+'\seal.json'' -Algorithm SHA256).Hash.ToLowerInvariant()-ne'''+$ExpectedSeal+'''){throw ''lease-v2-seal-drift''};'
if($Mode-eq'Dispatch'){
 $remote+='$cfg=Get-Content -LiteralPath '''+$root+'\lease-config.json'' -Raw|ConvertFrom-Json;if($cfg.profile-ceq''campaign-v2-extended''){$minutes=101;$taskDeadline=6060000}elseif($cfg.profile-ceq''campaign-v2''){$minutes=86;$taskDeadline=5160000}else{throw ''lease-v2-profile''};$name=''Runa-M1-'+$LeaseId+''';if(Get-ScheduledTask -TaskName $name -ErrorAction SilentlyContinue){throw ''lease-v2-task-exists''};$a=New-ScheduledTaskAction -Execute ''C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'' -Argument ''-NoProfile -NonInteractive -ExecutionPolicy Bypass -File "'+$root+'\Run-HomeCampaignLeaseV2.ps1"'';$p=New-ScheduledTaskPrincipal -UserId ''RUNA-HOME\codex-audit'' -LogonType S4U -RunLevel Highest;$s=New-ScheduledTaskSettingsSet -ExecutionTimeLimit (New-TimeSpan -Minutes $minutes) -MultipleInstances IgnoreNew -Hidden;$null=Register-ScheduledTask -TaskName $name -Action $a -Principal $p -Settings $s;Start-ScheduledTask -TaskName $name;@{dispatched=$true;leaseId='''+$LeaseId+''';sealSha256='''+$ExpectedSeal+''';taskDeadlineMs=$taskDeadline}|ConvertTo-Json -Compress'
}elseif($Mode-in@('Status','Cleanup')){
 $remote+='$name=''Runa-M1-'+$LeaseId+''';$task=Get-ScheduledTask -TaskName $name;$info=Get-ScheduledTaskInfo -TaskName $name;$ready=$null;$result=$null;$supervisor=$null;foreach($pair in @(@(''ready'',''ready.json''),@(''result'',''lease-result.json''),@(''supervisor'',''supervisor-result.json''))){$f=Join-Path '''+$root+''' $pair[1];if(Test-Path -LiteralPath $f){Set-Variable -Name $pair[0] -Value (Get-Content -LiteralPath $f -Raw|ConvertFrom-Json)}};'
 if($Mode-eq'Cleanup'){$remote+='if($task.State-eq''Running''-or$null-eq$supervisor-or-not$supervisor.zeroResidencyAndPowerRestored-or$task.Actions.Arguments-notlike''*'+$LeaseId+'\Run-HomeCampaignLeaseV2.ps1*''){throw ''lease-v2-task-cleanup-boundary''};Unregister-ScheduledTask -TaskName $name -Confirm:$false;'}
 $remote+='$last=$null;$f=Join-Path '''+$root+''' ''events.jsonl'';if(Test-Path -LiteralPath $f){$line=Get-Content -LiteralPath $f -Tail 1;if($line){$last=$line|ConvertFrom-Json|Select-Object type,time,phase,code,gpus}};@{taskState=[string]$task.State;taskExit=$info.LastTaskResult;ready=$ready;result=$result;supervisor=$supervisor;lastEvent=$last}|ConvertTo-Json -Depth 20 -Compress'
}elseif($Mode-eq'Final'){
 $remote+='$registry=Invoke-RestMethod -Uri ''http://127.0.0.1:1234/api/v1/models'' -TimeoutSec 10;$models=@($registry.models|ForEach-Object{@{key=$_.key;loadedInstances=@($_.loaded_instances)}});$gpus=@(& nvidia-smi.exe --query-gpu=index,uuid,power.limit,temperature.gpu,memory.total,memory.used --format=csv,noheader,nounits);$tasks=@(Get-ScheduledTask|Where-Object{$_.TaskName-match''^Runa-M1-20260829-campaign-(gemma|coder|qwen36)-r[1-9][0-9]*$''}|Select-Object TaskName,State);$ports=@(Get-NetTCPConnection -State Listen|Where-Object{$_.LocalPort-in@(1234,8412)}|Select-Object LocalAddress,LocalPort);[Console]::Out.Write((@{schemaVersion=''runa-m1-campaign-final-observation/v2'';time=[DateTime]::UtcNow.ToString(''o'');host=$env:COMPUTERNAME;models=$models;gpus=$gpus;ownedTaskRegistrations=$tasks;listeners=$ports;readOnly=$true;protectedDataIncluded=$false}|ConvertTo-Json -Depth 20))'
}elseif($Mode-eq'Export'){
 $remote+='$result=@{};foreach($f in Get-ChildItem -LiteralPath '''+$root+''' -File){if($f.Name-match''^(seal|lease-config|runtime|ready|complete|lease-result|worker|supervisor-result|campaign-hardware-plan)\.json$|^(events|supervisor)\.jsonl$|^worker-(stdout|stderr)\.txt$|^(home-campaign-lease-v2|lease-v2-contract|lease-contract|gguf-metadata)\.mjs$|^Run-HomeCampaignLeaseV2\.ps1$''){$result[$f.Name]=[Convert]::ToBase64String([IO.File]::ReadAllBytes($f.FullName))}};[Console]::Out.Write(($result|ConvertTo-Json -Compress))'
}else{$remote+='@{uploaded=$true;sealSha256='''+$ExpectedSeal+'''}|ConvertTo-Json -Compress'}
$encoded=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($remote));$info=New-Object Diagnostics.ProcessStartInfo
$info.FileName='ssh.exe';$info.Arguments='-F "C:\Users\matth\.ssh\config" -o ClearAllForwardings=yes runa-control-wsl-codex "ssh -o ClearAllForwardings=yes runa-home-codex powershell.exe -NoProfile -EncodedCommand '+$encoded+'"'
$info.UseShellExecute=$false;$info.CreateNoWindow=$true;$info.RedirectStandardInput=$true;$info.RedirectStandardOutput=$true;$info.RedirectStandardError=$true
$process=[Diagnostics.Process]::Start($info);$err=$process.StandardError.ReadToEndAsync()
if($Mode-eq'Upload'){$stream=[IO.File]::OpenRead([IO.Path]::GetFullPath($LocalFile));try{$stream.CopyTo($process.StandardInput.BaseStream)}finally{$stream.Dispose()}}
$process.StandardInput.Close()
if($Mode-in@('Export','Final')){$stream=[IO.File]::Open([IO.Path]::GetFullPath($LocalFile),[IO.FileMode]::CreateNew,[IO.FileAccess]::Write)
 try{$process.StandardOutput.BaseStream.CopyTo($stream)}finally{$stream.Dispose()}}else{while(-not$process.StandardOutput.EndOfStream){[Console]::Out.WriteLine($process.StandardOutput.ReadLine())}}
$process.WaitForExit();[Console]::Error.Write($err.GetAwaiter().GetResult());exit $process.ExitCode
